const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Realistic seed data for 30 venues in Hanoi
const seedData = async () => {
  console.log('🌱 Starting seed...');

  try {
    // Create admin user
    const adminUser = await prisma.user.upsert({
      where: { phone: '0900000000' },
      update: {},
      create: {
        phone: '0900000000',
        email: 'admin@sportmatch.vn',
        name: 'Admin SportMatch',
        role: 'admin',
        isActive: true
      }
    });

    console.log('✅ Admin user created');

    // Create venue owners
    const owners = await Promise.all([
      prisma.user.upsert({
        where: { phone: '0901111111' },
        update: {},
        create: {
          phone: '0901111111',
          name: 'Nguyễn Văn A',
          role: 'venue_owner'
        }
      }),
      prisma.user.upsert({
        where: { phone: '0902222222' },
        update: {},
        create: {
          phone: '0902222222',
          name: 'Trần Thị B',
          role: 'venue_owner'
        }
      }),
      prisma.user.upsert({
        where: { phone: '0903333333' },
        update: {},
        create: {
          phone: '0903333333',
          name: 'Lê Văn C',
          role: 'venue_owner'
        }
      }),
      prisma.user.upsert({
        where: { phone: '0904444444' },
        update: {},
        create: {
          phone: '0904444444',
          name: 'Phạm Minh D',
          role: 'venue_owner'
        }
      }),
      prisma.user.upsert({
        where: { phone: '0905555555' },
        update: {},
        create: {
          phone: '0905555555',
          name: 'Hoàng Thu E',
          role: 'venue_owner'
        }
      })
    ]);

    console.log('✅ Venue owners created');

    // 30 realistic venues in Hanoi
    const venues = [
      // === BADMINTON VENUES (20 venues) ===
      {
        name: 'Sân Cầu Lông VinSport - Cầu Giấy',
        description: 'Sân cầu lông cao cấp với 12 sân tiêu chuẩn quốc tế, điều hòa mát mẻ, ánh sáng LED chuyên dụng',
        address: '458 Minh Khai, Hai Bà Trưng, Hà Nội',
        location: { lat: 21.0050396, lng: 105.8579576 },
        sportType: 'badminton',
        phone: '0901234567',
        courtWidthType: 'wide',
        surfaceType: 'plastic',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 550,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 40,
        ventilation: 'enclosed',
        avgTemperature: 24,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 50000,
        hasDrinkService: true,
        images: ['/images/vinsport1.jpg', '/images/vinsport2.jpg'],
        ratingSurface: 4.8,
        ratingLighting: 4.9,
        ratingCleanliness: 4.9,
        ratingAmenities: 4.8,
        ratingPrice: 4.0,
        ratingService: 4.7,
        ratingOverall: 4.7,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 4, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Cầu Lông Thiên Thanh - Đống Đa',
        description: 'Sân cầu lông giá rẻ, phù hợp người mới chơi và học sinh sinh viên',
        address: '234 Thái Hà, Đống Đa, Hà Nội',
        location: { lat: 21.0138889, lng: 105.8180556 },
        sportType: 'badminton',
        phone: '0907654321',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 350,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 55,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: false,
        hasFreeWifi: false,
        hasAC: false,
        standardBallBrand: 'Victor',
        images: ['/images/thienthanh1.jpg'],
        ratingSurface: 3.8,
        ratingLighting: 3.5,
        ratingCleanliness: 3.6,
        ratingAmenities: 3.0,
        ratingPrice: 4.5,
        ratingService: 3.8,
        ratingOverall: 3.7,
        ownerId: owners[1].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 120000, priceWeekendMorning: 70000, priceWeekendAfternoon: 100000, priceWeekendEvening: 140000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 120000, priceWeekendMorning: 70000, priceWeekendAfternoon: 100000, priceWeekendEvening: 140000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Sân Cầu Lông Hoàng Quốc Việt',
        description: 'Sân cầu lông chất lượng cao, sạch sẽ, thoáng mát với biên sân rộng',
        address: '123 Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
        location: { lat: 21.0327777, lng: 105.7945555 },
        sportType: 'badminton',
        phone: '0912345678',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 500,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 45,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 40000,
        images: ['/images/hqv1.jpg', '/images/hqv2.jpg'],
        ratingSurface: 4.6,
        ratingLighting: 4.7,
        ratingCleanliness: 4.6,
        ratingAmenities: 4.5,
        ratingPrice: 4.2,
        ratingService: 4.5,
        ratingOverall: 4.5,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '05:30', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '05:30', operatingHoursEnd: '23:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '05:30', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Cầu Lông Nguyễn Trãi - Thanh Xuân',
        description: 'Sân cầu lông trong khu dân cư, tiện lợi, giá cả phải chăng',
        address: '567 Nguyễn Trãi, Thanh Xuân, Hà Nội',
        location: { lat: 20.9981111, lng: 105.8077777 },
        sportType: 'badminton',
        phone: '0913456789',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 400,
        hasAntiGlare: false,
        lightingQuality: 'good',
        noiseLevel: 50,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: false,
        standardBallBrand: 'Lining',
        hasRacketRental: false,
        images: ['/images/nguyentrai1.jpg'],
        ratingSurface: 4.0,
        ratingLighting: 4.1,
        ratingCleanliness: 4.2,
        ratingAmenities: 3.5,
        ratingPrice: 4.3,
        ratingService: 4.0,
        ratingOverall: 4.0,
        ownerId: owners[2].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 60000, priceWeekdayAfternoon: 80000, priceWeekdayEvening: 140000, priceWeekendMorning: 80000, priceWeekendAfternoon: 110000, priceWeekendEvening: 160000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 60000, priceWeekdayAfternoon: 80000, priceWeekdayEvening: 140000, priceWeekendMorning: 80000, priceWeekendAfternoon: 110000, priceWeekendEvening: 160000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 60000, priceWeekdayAfternoon: 80000, priceWeekdayEvening: 140000, priceWeekendMorning: 80000, priceWeekendAfternoon: 110000, priceWeekendEvening: 160000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' }
        ]
      },
      {
        name: 'Cầu Lông Thăng Long Elite - Mỹ Đình',
        description: 'Sân cầu lông VIP với camera livestream, điều hòa trung tâm, mặt sân gỗ 3 lớp',
        address: '88 Phạm Hùng, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0284444, lng: 105.7797222 },
        sportType: 'badminton',
        phone: '0924567890',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 600,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 35,
        ventilation: 'enclosed',
        avgTemperature: 23,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 60000,
        hasDrinkService: true,
        images: ['/images/thanglong1.jpg', '/images/thanglong2.jpg'],
        ratingSurface: 4.9,
        ratingLighting: 5.0,
        ratingCleanliness: 4.9,
        ratingAmenities: 4.9,
        ratingPrice: 3.8,
        ratingService: 4.8,
        ratingOverall: 4.7,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 100000, priceWeekdayAfternoon: 120000, priceWeekdayEvening: 220000, priceWeekendMorning: 120000, priceWeekendAfternoon: 180000, priceWeekendEvening: 250000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 100000, priceWeekdayAfternoon: 120000, priceWeekdayEvening: 220000, priceWeekendMorning: 120000, priceWeekendAfternoon: 180000, priceWeekendEvening: 250000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 100000, priceWeekdayAfternoon: 120000, priceWeekdayEvening: 220000, priceWeekendMorning: 120000, priceWeekendAfternoon: 180000, priceWeekendEvening: 250000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 4, sportType: 'badminton', priceWeekdayMorning: 100000, priceWeekdayAfternoon: 120000, priceWeekdayEvening: 220000, priceWeekendMorning: 120000, priceWeekendAfternoon: 180000, priceWeekendEvening: 250000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 5, sportType: 'badminton', priceWeekdayMorning: 100000, priceWeekdayAfternoon: 120000, priceWeekdayEvening: 220000, priceWeekendMorning: 120000, priceWeekendAfternoon: 180000, priceWeekendEvening: 250000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' }
        ]
      },
      {
        name: 'Cầu Lông Giảng Võ - Ba Đình',
        description: 'Sân cầu lông giữa trung tâm thành phố, gần Hồ Gươm',
        address: '45 Giảng Võ, Ba Đình, Hà Nội',
        location: { lat: 21.0291666, lng: 105.8172222 },
        sportType: 'badminton',
        phone: '0935678901',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 380,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 60,
        ventilation: 'semi_enclosed',
        freeParking: false,
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: false,
        hasFreeWifi: false,
        hasAC: false,
        standardBallBrand: 'Victor',
        images: ['/images/giangvo1.jpg'],
        ratingSurface: 3.5,
        ratingLighting: 3.4,
        ratingCleanliness: 3.2,
        ratingAmenities: 2.8,
        ratingPrice: 4.6,
        ratingService: 3.5,
        ratingOverall: 3.5,
        ownerId: owners[3].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 65000, priceWeekdayEvening: 110000, priceWeekendMorning: 65000, priceWeekendAfternoon: 90000, priceWeekendEvening: 130000, operatingHoursStart: '06:30', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 65000, priceWeekdayEvening: 110000, priceWeekendMorning: 65000, priceWeekendAfternoon: 90000, priceWeekendEvening: 130000, operatingHoursStart: '06:30', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Cầu Lông Kim Mã Premium',
        description: 'Sân cầu lông cao cấp tại khu Kim Mã, mặt sân gỗ, ánh sáng tự nhiên kết hợp LED',
        address: '234 Kim Mã, Ba Đình, Hà Nội',
        location: { lat: 21.0313888, lng: 105.8183333 },
        sportType: 'badminton',
        phone: '0946789012',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 520,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 42,
        ventilation: 'enclosed',
        avgTemperature: 24,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 50000,
        hasDrinkService: true,
        images: ['/images/kimma1.jpg', '/images/kimma2.jpg'],
        ratingSurface: 4.7,
        ratingLighting: 4.8,
        ratingCleanliness: 4.8,
        ratingAmenities: 4.7,
        ratingPrice: 3.9,
        ratingService: 4.6,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 90000, priceWeekdayAfternoon: 110000, priceWeekdayEvening: 200000, priceWeekendMorning: 110000, priceWeekendAfternoon: 160000, priceWeekendEvening: 230000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 90000, priceWeekdayAfternoon: 110000, priceWeekdayEvening: 200000, priceWeekendMorning: 110000, priceWeekendAfternoon: 160000, priceWeekendEvening: 230000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 90000, priceWeekdayAfternoon: 110000, priceWeekdayEvening: 200000, priceWeekendMorning: 110000, priceWeekendAfternoon: 160000, priceWeekendEvening: 230000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Cầu Lông Đại Cồ Việt - Hai Bà Trưng',
        description: 'Sân cầu lông gần trường đại học, giá sinh viên, sạch sẽ',
        address: '78 Đại Cồ Việt, Hai Bà Trưng, Hà Nội',
        location: { lat: 21.0044444, lng: 105.8436111 },
        sportType: 'badminton',
        phone: '0957890123',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'clean',
        lightingType: 'fluorescent',
        lightingLux: 360,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 52,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: false,
        standardBallBrand: 'Lining',
        hasRacketRental: true,
        racketRentalPrice: 30000,
        images: ['/images/daicoviet1.jpg'],
        ratingSurface: 3.9,
        ratingLighting: 3.7,
        ratingCleanliness: 4.0,
        ratingAmenities: 3.4,
        ratingPrice: 4.5,
        ratingService: 3.9,
        ratingOverall: 3.9,
        ownerId: owners[2].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 55000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 130000, priceWeekendMorning: 75000, priceWeekendAfternoon: 105000, priceWeekendEvening: 150000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 55000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 130000, priceWeekendMorning: 75000, priceWeekendAfternoon: 105000, priceWeekendEvening: 150000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 55000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 130000, priceWeekendMorning: 75000, priceWeekendAfternoon: 105000, priceWeekendEvening: 150000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Cầu Lông Láng Hạ Sport',
        description: 'Sân cầu lông trung tâm, tiện lợi cho dân văn phòng',
        address: '156 Láng Hạ, Đống Đa, Hà Nội',
        location: { lat: 21.0155555, lng: 105.8130555 },
        sportType: 'badminton',
        phone: '0968901234',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'medium',
        lightingType: 'led',
        lightingLux: 420,
        hasAntiGlare: false,
        lightingQuality: 'good',
        noiseLevel: 55,
        ventilation: 'semi_enclosed',
        freeParking: false,
        hasLockerRoom: true,
        lockerRoomQuality: 3,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: false,
        hasFreeWifi: true,
        hasAC: false,
        standardBallBrand: 'Victor',
        images: ['/images/langha1.jpg'],
        ratingSurface: 4.0,
        ratingLighting: 4.2,
        ratingCleanliness: 3.8,
        ratingAmenities: 3.6,
        ratingPrice: 4.1,
        ratingService: 4.0,
        ratingOverall: 3.9,
        ownerId: owners[1].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 65000, priceWeekdayAfternoon: 85000, priceWeekdayEvening: 150000, priceWeekendMorning: 85000, priceWeekendAfternoon: 120000, priceWeekendEvening: 170000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 65000, priceWeekdayAfternoon: 85000, priceWeekdayEvening: 150000, priceWeekendMorning: 85000, priceWeekendAfternoon: 120000, priceWeekendEvening: 170000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' }
        ]
      },
      {
        name: 'Cầu Lông Trần Duy Hưng - Trung Hòa',
        description: 'Sân cầu lông trong khu đô thị Trung Hòa Nhân Chính',
        address: '89 Trần Duy Hưng, Cầu Giấy, Hà Nội',
        location: { lat: 21.0097222, lng: 105.7972222 },
        sportType: 'badminton',
        phone: '0979012345',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 450,
        hasAntiGlare: true,
        lightingQuality: 'good',
        noiseLevel: 48,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 45000,
        images: ['/images/tranduyhung1.jpg'],
        ratingSurface: 4.3,
        ratingLighting: 4.4,
        ratingCleanliness: 4.3,
        ratingAmenities: 4.2,
        ratingPrice: 4.0,
        ratingService: 4.2,
        ratingOverall: 4.2,
        ownerId: owners[0].id,
        subscriptionTier: 'basic',
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 75000, priceWeekdayAfternoon: 95000, priceWeekdayEvening: 170000, priceWeekendMorning: 95000, priceWeekendAfternoon: 140000, priceWeekendEvening: 190000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 75000, priceWeekdayAfternoon: 95000, priceWeekdayEvening: 170000, priceWeekendMorning: 95000, priceWeekendAfternoon: 140000, priceWeekendEvening: 190000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 75000, priceWeekdayAfternoon: 95000, priceWeekdayEvening: 170000, priceWeekendMorning: 95000, priceWeekendAfternoon: 140000, priceWeekendEvening: 190000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Cầu Lông Long Biên Central',
        description: 'Sân cầu lông phục vụ khu vực Long Biên, giá tốt',
        address: '345 Nguyễn Văn Cừ, Long Biên, Hà Nội',
        location: { lat: 21.0422222, lng: 105.8688888 },
        sportType: 'badminton',
        phone: '0981234567',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 340,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 58,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: false,
        hasFreeWifi: false,
        hasAC: false,
        standardBallBrand: 'Lining',
        images: ['/images/longbien1.jpg'],
        ratingSurface: 3.6,
        ratingLighting: 3.3,
        ratingCleanliness: 3.5,
        ratingAmenities: 3.0,
        ratingPrice: 4.4,
        ratingService: 3.6,
        ratingOverall: 3.6,
        ownerId: owners[3].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 45000, priceWeekdayAfternoon: 60000, priceWeekdayEvening: 110000, priceWeekendMorning: 65000, priceWeekendAfternoon: 90000, priceWeekendEvening: 130000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 45000, priceWeekdayAfternoon: 60000, priceWeekdayEvening: 110000, priceWeekendMorning: 65000, priceWeekendAfternoon: 90000, priceWeekendEvening: 130000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Cầu Lông Tây Hồ Premium',
        description: 'Sân cầu lông cao cấp view Hồ Tây, không gian thoáng đãng',
        address: '67 Lạc Long Quân, Tây Hồ, Hà Nội',
        location: { lat: 21.0527777, lng: 105.8161111 },
        sportType: 'badminton',
        phone: '0992345678',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 580,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 38,
        ventilation: 'enclosed',
        avgTemperature: 23,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 70000,
        hasDrinkService: true,
        images: ['/images/tayho1.jpg', '/images/tayho2.jpg'],
        ratingSurface: 4.9,
        ratingLighting: 4.9,
        ratingCleanliness: 5.0,
        ratingAmenities: 4.8,
        ratingPrice: 3.5,
        ratingService: 4.9,
        ratingOverall: 4.7,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 120000, priceWeekdayAfternoon: 150000, priceWeekdayEvening: 250000, priceWeekendMorning: 150000, priceWeekendAfternoon: 200000, priceWeekendEvening: 280000, operatingHoursStart: '05:30', operatingHoursEnd: '23:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 120000, priceWeekdayAfternoon: 150000, priceWeekdayEvening: 250000, priceWeekendMorning: 150000, priceWeekendAfternoon: 200000, priceWeekendEvening: 280000, operatingHoursStart: '05:30', operatingHoursEnd: '23:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 120000, priceWeekdayAfternoon: 150000, priceWeekdayEvening: 250000, priceWeekendMorning: 150000, priceWeekendAfternoon: 200000, priceWeekendEvening: 280000, operatingHoursStart: '05:30', operatingHoursEnd: '23:30' }
        ]
      },
      {
        name: 'Cầu Lông Xuân Thủy - Cầu Giấy',
        description: 'Sân cầu lông gần khu đô thị mới, tiện nghi đầy đủ',
        address: '199 Xuân Thủy, Cầu Giấy, Hà Nội',
        location: { lat: 21.0380555, lng: 105.7941666 },
        sportType: 'badminton',
        phone: '0903456789',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 480,
        hasAntiGlare: true,
        lightingQuality: 'good',
        noiseLevel: 44,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Victor',
        hasRacketRental: true,
        racketRentalPrice: 40000,
        images: ['/images/xuanthuy1.jpg'],
        ratingSurface: 4.4,
        ratingLighting: 4.5,
        ratingCleanliness: 4.4,
        ratingAmenities: 4.3,
        ratingPrice: 4.1,
        ratingService: 4.3,
        ratingOverall: 4.3,
        ownerId: owners[1].id,
        subscriptionTier: 'basic',
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 70000, priceWeekdayAfternoon: 90000, priceWeekdayEvening: 160000, priceWeekendMorning: 90000, priceWeekendAfternoon: 130000, priceWeekendEvening: 180000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' }
        ]
      },
      {
        name: 'Cầu Lông Hào Nam - Đống Đa',
        description: 'Sân cầu lông giá sinh viên, gần Học viện Báo chí',
        address: '23 Hào Nam, Đống Đa, Hà Nội',
        location: { lat: 21.0172222, lng: 105.8238888 },
        sportType: 'badminton',
        phone: '0914567890',
        courtWidthType: 'narrow',
        surfaceType: 'plastic',
        surfaceLayers: 1,
        elasticity: 'low',
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 300,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 62,
        ventilation: 'open',
        freeParking: false,
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 2,
        hasCanteen: false,
        hasFreeWifi: false,
        hasAC: false,
        standardBallBrand: 'Lining',
        images: ['/images/haonam1.jpg'],
        ratingSurface: 3.0,
        ratingLighting: 3.0,
        ratingCleanliness: 2.9,
        ratingAmenities: 2.5,
        ratingPrice: 4.8,
        ratingService: 3.2,
        ratingOverall: 3.2,
        ownerId: owners[4].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 40000, priceWeekdayAfternoon: 55000, priceWeekdayEvening: 100000, priceWeekendMorning: 60000, priceWeekendAfternoon: 85000, priceWeekendEvening: 120000, operatingHoursStart: '06:30', operatingHoursEnd: '21:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 40000, priceWeekdayAfternoon: 55000, priceWeekdayEvening: 100000, priceWeekendMorning: 60000, priceWeekendAfternoon: 85000, priceWeekendEvening: 120000, operatingHoursStart: '06:30', operatingHoursEnd: '21:30' }
        ]
      },
      {
        name: 'Cầu Lông Yên Hòa - Cầu Giấy',
        description: 'Sân cầu lông trong khu dân cư Yên Hòa, tiện lợi',
        address: '112 Trần Cung, Cầu Giấy, Hà Nội',
        location: { lat: 21.0380555, lng: 105.7877777 },
        sportType: 'badminton',
        phone: '0925678901',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 400,
        hasAntiGlare: false,
        lightingQuality: 'good',
        noiseLevel: 50,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: false,
        standardBallBrand: 'Victor',
        hasRacketRental: false,
        images: ['/images/yenhoa1.jpg'],
        ratingSurface: 4.0,
        ratingLighting: 4.0,
        ratingCleanliness: 4.1,
        ratingAmenities: 3.5,
        ratingPrice: 4.2,
        ratingService: 3.9,
        ratingOverall: 3.9,
        ownerId: owners[2].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 60000, priceWeekdayAfternoon: 80000, priceWeekdayEvening: 145000, priceWeekendMorning: 80000, priceWeekendAfternoon: 115000, priceWeekendEvening: 165000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 60000, priceWeekdayAfternoon: 80000, priceWeekdayEvening: 145000, priceWeekendMorning: 80000, priceWeekendAfternoon: 115000, priceWeekendEvening: 165000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Cầu Lông Vạn Phúc - Hà Đông',
        description: 'Sân cầu lông mới xây tại khu đô thị Vạn Phúc, cơ sở vật chất hiện đại',
        address: '45 Tố Hữu, Hà Đông, Hà Nội',
        location: { lat: 20.9797222, lng: 105.7636111 },
        sportType: 'badminton',
        phone: '0936789012',
        courtWidthType: 'wide',
        surfaceType: 'plastic',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 500,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 40,
        ventilation: 'enclosed',
        avgTemperature: 25,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 50000,
        hasDrinkService: true,
        images: ['/images/vanphuc1.jpg', '/images/vanphuc2.jpg'],
        ratingSurface: 4.8,
        ratingLighting: 4.8,
        ratingCleanliness: 4.9,
        ratingAmenities: 4.7,
        ratingPrice: 4.0,
        ratingService: 4.7,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 4, sportType: 'badminton', priceWeekdayMorning: 80000, priceWeekdayAfternoon: 100000, priceWeekdayEvening: 180000, priceWeekendMorning: 100000, priceWeekendAfternoon: 150000, priceWeekendEvening: 200000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Cầu Lông Linh Đàm - Hoàng Mai',
        description: 'Sân cầu lông tại khu đô thị Linh Đàm, phục vụ cộng đồng dân cư',
        address: '234 Hoàng Liệt, Hoàng Mai, Hà Nội',
        location: { lat: 20.9736111, lng: 105.8322222 },
        sportType: 'badminton',
        phone: '0947890123',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 370,
        hasAntiGlare: false,
        lightingQuality: 'adequate',
        noiseLevel: 54,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: true,
        hasFreeWifi: false,
        hasAC: false,
        standardBallBrand: 'Lining',
        images: ['/images/linhdam1.jpg'],
        ratingSurface: 3.7,
        ratingLighting: 3.6,
        ratingCleanliness: 3.5,
        ratingAmenities: 3.3,
        ratingPrice: 4.4,
        ratingService: 3.7,
        ratingOverall: 3.7,
        ownerId: owners[3].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 125000, priceWeekendMorning: 70000, priceWeekendAfternoon: 100000, priceWeekendEvening: 145000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 50000, priceWeekdayAfternoon: 70000, priceWeekdayEvening: 125000, priceWeekendMorning: 70000, priceWeekendAfternoon: 100000, priceWeekendEvening: 145000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Cầu Lông Mễ Trì - Nam Từ Liêm',
        description: 'Sân cầu lông gần Mỹ Đình, tiện lợi sau giờ làm việc',
        address: '78 Mễ Trì Hạ, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0236111, lng: 105.7741666 },
        sportType: 'badminton',
        phone: '0958901234',
        courtWidthType: 'standard',
        surfaceType: 'plastic',
        surfaceLayers: 2,
        elasticity: 'medium',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 430,
        hasAntiGlare: true,
        lightingQuality: 'good',
        noiseLevel: 47,
        ventilation: 'semi_enclosed',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: false,
        standardBallBrand: 'Victor',
        hasRacketRental: true,
        racketRentalPrice: 35000,
        images: ['/images/metri1.jpg'],
        ratingSurface: 4.2,
        ratingLighting: 4.3,
        ratingCleanliness: 4.2,
        ratingAmenities: 4.0,
        ratingPrice: 4.1,
        ratingService: 4.1,
        ratingOverall: 4.1,
        ownerId: owners[1].id,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 65000, priceWeekdayAfternoon: 85000, priceWeekdayEvening: 155000, priceWeekendMorning: 85000, priceWeekendAfternoon: 125000, priceWeekendEvening: 175000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 65000, priceWeekdayAfternoon: 85000, priceWeekdayEvening: 155000, priceWeekendMorning: 85000, priceWeekendAfternoon: 125000, priceWeekendEvening: 175000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 65000, priceWeekdayAfternoon: 85000, priceWeekdayEvening: 155000, priceWeekendMorning: 85000, priceWeekendAfternoon: 125000, priceWeekendEvening: 175000, operatingHoursStart: '06:00', operatingHoursEnd: '22:30' }
        ]
      },
      {
        name: 'Cầu Lông Đỗ Đức Dục - Mễ Trì',
        description: 'Sân cầu lông cao cấp mới khai trương, cơ sở vật chất hiện đại',
        address: '156 Đỗ Đức Dục, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0194444, lng: 105.7688888 },
        sportType: 'badminton',
        phone: '0969012345',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 570,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 36,
        ventilation: 'enclosed',
        avgTemperature: 23,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 60000,
        hasDrinkService: true,
        images: ['/images/doducduc1.jpg', '/images/doducduc2.jpg'],
        ratingSurface: 4.9,
        ratingLighting: 5.0,
        ratingCleanliness: 4.9,
        ratingAmenities: 4.9,
        ratingPrice: 3.7,
        ratingService: 4.8,
        ratingOverall: 4.7,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 110000, priceWeekdayAfternoon: 130000, priceWeekdayEvening: 230000, priceWeekendMorning: 130000, priceWeekendAfternoon: 180000, priceWeekendEvening: 260000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 110000, priceWeekdayAfternoon: 130000, priceWeekdayEvening: 230000, priceWeekendMorning: 130000, priceWeekendAfternoon: 180000, priceWeekendEvening: 260000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 110000, priceWeekdayAfternoon: 130000, priceWeekdayEvening: 230000, priceWeekendMorning: 130000, priceWeekendAfternoon: 180000, priceWeekendEvening: 260000, operatingHoursStart: '05:00', operatingHoursEnd: '23:30' }
        ]
      },
      {
        name: 'Cầu Lông Royal City - Thanh Xuân',
        description: 'Sân cầu lông trong tòa nhà Royal City, cao cấp, tiện nghi 5 sao',
        address: 'Royal City, 72A Nguyễn Trãi, Thanh Xuân, Hà Nội',
        location: { lat: 20.9988888, lng: 105.8155555 },
        sportType: 'badminton',
        phone: '0971234567',
        courtWidthType: 'wide',
        surfaceType: 'wood',
        surfaceLayers: 3,
        elasticity: 'high',
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 620,
        hasAntiGlare: true,
        lightingQuality: 'excellent',
        noiseLevel: 32,
        ventilation: 'enclosed',
        avgTemperature: 22,
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        hasAC: true,
        standardBallBrand: 'Yonex',
        hasRacketRental: true,
        racketRentalPrice: 80000,
        hasDrinkService: true,
        images: ['/images/royalcity1.jpg', '/images/royalcity2.jpg', '/images/royalcity3.jpg'],
        ratingSurface: 5.0,
        ratingLighting: 5.0,
        ratingCleanliness: 5.0,
        ratingAmenities: 5.0,
        ratingPrice: 3.2,
        ratingService: 5.0,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'badminton', priceWeekdayMorning: 150000, priceWeekdayAfternoon: 180000, priceWeekdayEvening: 280000, priceWeekendMorning: 180000, priceWeekendAfternoon: 230000, priceWeekendEvening: 300000, operatingHoursStart: '05:00', operatingHoursEnd: '24:00' },
          { number: 2, sportType: 'badminton', priceWeekdayMorning: 150000, priceWeekdayAfternoon: 180000, priceWeekdayEvening: 280000, priceWeekendMorning: 180000, priceWeekendAfternoon: 230000, priceWeekendEvening: 300000, operatingHoursStart: '05:00', operatingHoursEnd: '24:00' },
          { number: 3, sportType: 'badminton', priceWeekdayMorning: 150000, priceWeekdayAfternoon: 180000, priceWeekdayEvening: 280000, priceWeekendMorning: 180000, priceWeekendAfternoon: 230000, priceWeekendEvening: 300000, operatingHoursStart: '05:00', operatingHoursEnd: '24:00' }
        ]
      },

      // === FOOTBALL VENUES (6 venues) ===
      {
        name: 'Sân Bóng Đá Mỹ Đình Mini',
        description: 'Sân bóng đá 5vs5 và 7vs7, cỏ nhân tạo chất lượng cao, ánh sáng LED',
        address: '12 Lê Quang Đạo, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0297222, lng: 105.7763888 },
        sportType: 'football',
        phone: '0982345678',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 2,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 480,
        hasAntiGlare: true,
        noiseLevel: 65,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Nike',
        images: ['/images/mydinh-football1.jpg'],
        ratingSurface: 4.5,
        ratingLighting: 4.6,
        ratingCleanliness: 4.4,
        ratingAmenities: 4.3,
        ratingPrice: 4.0,
        ratingService: 4.4,
        ratingOverall: 4.4,
        ownerId: owners[1].id,
        subscriptionTier: 'basic',
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5 A', priceWeekdayMorning: 300000, priceWeekdayAfternoon: 400000, priceWeekdayEvening: 600000, priceWeekendMorning: 400000, priceWeekendAfternoon: 550000, priceWeekendEvening: 700000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'football', name: 'Sân 7vs7 B', priceWeekdayMorning: 500000, priceWeekdayAfternoon: 650000, priceWeekdayEvening: 900000, priceWeekendMorning: 650000, priceWeekendAfternoon: 850000, priceWeekendEvening: 1000000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Sân Bóng The Giao - Tây Hồ',
        description: 'Sân bóng đá cỏ nhân tạo cao cấp, view Hồ Tây đẹp',
        address: '234 Lạc Long Quân, Tây Hồ, Hà Nội',
        location: { lat: 21.0541666, lng: 105.8077777 },
        sportType: 'football',
        phone: '0993456789',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 3,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 500,
        hasAntiGlare: true,
        noiseLevel: 60,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Adidas',
        images: ['/images/thegiao1.jpg', '/images/thegiao2.jpg'],
        ratingSurface: 4.7,
        ratingLighting: 4.8,
        ratingCleanliness: 4.7,
        ratingAmenities: 4.6,
        ratingPrice: 3.8,
        ratingService: 4.7,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5', priceWeekdayMorning: 350000, priceWeekdayAfternoon: 450000, priceWeekdayEvening: 700000, priceWeekendMorning: 450000, priceWeekendAfternoon: 600000, priceWeekendEvening: 800000, operatingHoursStart: '05:30', operatingHoursEnd: '23:30' },
          { number: 2, sportType: 'football', name: 'Sân 7vs7', priceWeekdayMorning: 600000, priceWeekdayAfternoon: 750000, priceWeekdayEvening: 1100000, priceWeekendMorning: 750000, priceWeekendAfternoon: 950000, priceWeekendEvening: 1200000, operatingHoursStart: '05:30', operatingHoursEnd: '23:30' }
        ]
      },
      {
        name: 'Sân Bóng Đá Hào Nam',
        description: 'Sân bóng đá mini giá rẻ cho sinh viên',
        address: '67 Hào Nam, Đống Đa, Hà Nội',
        location: { lat: 21.0183333, lng: 105.8250000 },
        sportType: 'football',
        phone: '0904567890',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 1,
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 350,
        hasAntiGlare: false,
        noiseLevel: 70,
        ventilation: 'open',
        freeParking: false,
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 2,
        hasCanteen: false,
        hasFreeWifi: false,
        standardBallBrand: 'Mikasa',
        images: ['/images/haonam-football1.jpg'],
        ratingSurface: 3.2,
        ratingLighting: 3.0,
        ratingCleanliness: 3.0,
        ratingAmenities: 2.7,
        ratingPrice: 4.7,
        ratingService: 3.3,
        ratingOverall: 3.3,
        ownerId: owners[4].id,
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5', priceWeekdayMorning: 250000, priceWeekdayAfternoon: 350000, priceWeekdayEvening: 500000, priceWeekendMorning: 350000, priceWeekendAfternoon: 450000, priceWeekendEvening: 600000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Sân Bóng Đá Keangnam',
        description: 'Sân bóng đá trong tòa nhà Keangnam, cỏ nhân tạo cao cấp',
        address: 'Keangnam Landmark, Phạm Hùng, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0169444, lng: 105.7813888 },
        sportType: 'football',
        phone: '0915678901',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 3,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 550,
        hasAntiGlare: true,
        noiseLevel: 55,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Adidas',
        images: ['/images/keangnam1.jpg'],
        ratingSurface: 4.8,
        ratingLighting: 4.9,
        ratingCleanliness: 4.8,
        ratingAmenities: 4.8,
        ratingPrice: 3.5,
        ratingService: 4.8,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5', priceWeekdayMorning: 400000, priceWeekdayAfternoon: 500000, priceWeekdayEvening: 800000, priceWeekendMorning: 500000, priceWeekendAfternoon: 700000, priceWeekendEvening: 900000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Sân Bóng Đá Times City',
        description: 'Sân bóng đá trong khu đô thị Times City, tiện nghi hiện đại',
        address: 'Times City, 458 Minh Khai, Hai Bà Trưng, Hà Nội',
        location: { lat: 21.0058333, lng: 105.8594444 },
        sportType: 'football',
        phone: '0926789012',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 2,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 470,
        hasAntiGlare: true,
        noiseLevel: 58,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Nike',
        images: ['/images/timescity1.jpg'],
        ratingSurface: 4.4,
        ratingLighting: 4.5,
        ratingCleanliness: 4.4,
        ratingAmenities: 4.4,
        ratingPrice: 3.9,
        ratingService: 4.4,
        ratingOverall: 4.3,
        ownerId: owners[1].id,
        subscriptionTier: 'basic',
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5', priceWeekdayMorning: 320000, priceWeekdayAfternoon: 420000, priceWeekdayEvening: 650000, priceWeekendMorning: 420000, priceWeekendAfternoon: 570000, priceWeekendEvening: 750000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'football', name: 'Sân 7vs7', priceWeekdayMorning: 550000, priceWeekdayAfternoon: 700000, priceWeekdayEvening: 1000000, priceWeekendMorning: 700000, priceWeekendAfternoon: 900000, priceWeekendEvening: 1150000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },
      {
        name: 'Sân Bóng Đá Vạn Phúc City',
        description: 'Sân bóng đá mới xây tại khu đô thị Vạn Phúc, cỏ nhân tạo 3 lớp',
        address: 'Vạn Phúc City, Tố Hữu, Hà Đông, Hà Nội',
        location: { lat: 20.9805555, lng: 105.7650000 },
        sportType: 'football',
        phone: '0937890123',
        courtWidthType: 'standard',
        surfaceType: 'artificial_grass',
        surfaceLayers: 3,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 520,
        hasAntiGlare: true,
        noiseLevel: 60,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Nike',
        images: ['/images/vanphuc-football1.jpg'],
        ratingSurface: 4.6,
        ratingLighting: 4.7,
        ratingCleanliness: 4.7,
        ratingAmenities: 4.5,
        ratingPrice: 4.0,
        ratingService: 4.6,
        ratingOverall: 4.5,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        courts: [
          { number: 1, sportType: 'football', name: 'Sân 5vs5 A', priceWeekdayMorning: 300000, priceWeekdayAfternoon: 400000, priceWeekdayEvening: 600000, priceWeekendMorning: 400000, priceWeekendAfternoon: 550000, priceWeekendEvening: 700000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' },
          { number: 2, sportType: 'football', name: 'Sân 5vs5 B', priceWeekdayMorning: 300000, priceWeekdayAfternoon: 400000, priceWeekdayEvening: 600000, priceWeekendMorning: 400000, priceWeekendAfternoon: 550000, priceWeekendEvening: 700000, operatingHoursStart: '06:00', operatingHoursEnd: '23:00' }
        ]
      },

      // === TENNIS VENUES (4 venues) ===
      {
        name: 'Sân Tennis Ciputra - Tây Hồ',
        description: 'Sân tennis cao cấp với mặt sân đất nện và cứng, ánh sáng LED chuyên dụng',
        address: 'Ciputra, Phạm Văn Đồng, Bắc Từ Liêm, Hà Nội',
        location: { lat: 21.0505555, lng: 105.7594444 },
        sportType: 'tennis',
        phone: '0948901234',
        courtWidthType: 'standard',
        surfaceType: 'hard_court',
        surfaceLayers: 2,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 500,
        hasAntiGlare: true,
        noiseLevel: 45,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Wilson',
        hasRacketRental: true,
        racketRentalPrice: 100000,
        images: ['/images/ciputra-tennis1.jpg'],
        ratingSurface: 4.7,
        ratingLighting: 4.8,
        ratingCleanliness: 4.8,
        ratingAmenities: 4.7,
        ratingPrice: 3.6,
        ratingService: 4.7,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'tennis', priceWeekdayMorning: 200000, priceWeekdayAfternoon: 250000, priceWeekdayEvening: 350000, priceWeekendMorning: 250000, priceWeekendAfternoon: 320000, priceWeekendEvening: 400000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'tennis', priceWeekdayMorning: 200000, priceWeekdayAfternoon: 250000, priceWeekdayEvening: 350000, priceWeekendMorning: 250000, priceWeekendAfternoon: 320000, priceWeekendEvening: 400000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Sân Tennis Mỹ Đình',
        description: 'Sân tennis tiêu chuẩn quốc tế gần sân vận động Mỹ Đình',
        address: '45 Lê Quang Đạo, Nam Từ Liêm, Hà Nội',
        location: { lat: 21.0319444, lng: 105.7736111 },
        sportType: 'tennis',
        phone: '0959012345',
        courtWidthType: 'standard',
        surfaceType: 'hard_court',
        surfaceLayers: 2,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 480,
        hasAntiGlare: true,
        noiseLevel: 50,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 4,
        hasToilet: true,
        toiletQuality: 4,
        hasCanteen: false,
        hasFreeWifi: true,
        standardBallBrand: 'Head',
        hasRacketRental: true,
        racketRentalPrice: 80000,
        images: ['/images/mydinh-tennis1.jpg'],
        ratingSurface: 4.4,
        ratingLighting: 4.5,
        ratingCleanliness: 4.3,
        ratingAmenities: 4.1,
        ratingPrice: 4.0,
        ratingService: 4.3,
        ratingOverall: 4.3,
        ownerId: owners[1].id,
        subscriptionTier: 'basic',
        courts: [
          { number: 1, sportType: 'tennis', priceWeekdayMorning: 150000, priceWeekdayAfternoon: 200000, priceWeekdayEvening: 280000, priceWeekendMorning: 200000, priceWeekendAfternoon: 260000, priceWeekendEvening: 320000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' },
          { number: 2, sportType: 'tennis', priceWeekdayMorning: 150000, priceWeekdayAfternoon: 200000, priceWeekdayEvening: 280000, priceWeekendMorning: 200000, priceWeekendAfternoon: 260000, priceWeekendEvening: 320000, operatingHoursStart: '06:00', operatingHoursEnd: '22:00' }
        ]
      },
      {
        name: 'Sân Tennis Hồ Tây',
        description: 'Sân tennis view Hồ Tây, mặt sân cứng chất lượng cao',
        address: '123 Võ Chí Công, Tây Hồ, Hà Nội',
        location: { lat: 21.0558333, lng: 105.8100000 },
        sportType: 'tennis',
        phone: '0961234567',
        courtWidthType: 'standard',
        surfaceType: 'hard_court',
        surfaceLayers: 2,
        cleanliness: 'clean',
        lightingType: 'led',
        lightingLux: 520,
        hasAntiGlare: true,
        noiseLevel: 42,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'both',
        hasLockerRoom: true,
        lockerRoomQuality: 5,
        hasToilet: true,
        toiletQuality: 5,
        hasCanteen: true,
        hasFreeWifi: true,
        standardBallBrand: 'Wilson',
        hasRacketRental: true,
        racketRentalPrice: 120000,
        images: ['/images/hotay-tennis1.jpg', '/images/hotay-tennis2.jpg'],
        ratingSurface: 4.8,
        ratingLighting: 4.9,
        ratingCleanliness: 4.8,
        ratingAmenities: 4.7,
        ratingPrice: 3.4,
        ratingService: 4.8,
        ratingOverall: 4.6,
        ownerId: owners[0].id,
        subscriptionTier: 'pro',
        isVerified: true,
        courts: [
          { number: 1, sportType: 'tennis', priceWeekdayMorning: 220000, priceWeekdayAfternoon: 280000, priceWeekdayEvening: 380000, priceWeekendMorning: 280000, priceWeekendAfternoon: 350000, priceWeekendEvening: 450000, operatingHoursStart: '05:30', operatingHoursEnd: '22:30' }
        ]
      },
      {
        name: 'Sân Tennis Thanh Xuân',
        description: 'Sân tennis giá tốt, phù hợp tập luyện hàng ngày',
        address: '234 Khuất Duy Tiến, Thanh Xuân, Hà Nội',
        location: { lat: 20.9969444, lng: 105.8027777 },
        sportType: 'tennis',
        phone: '0972345678',
        courtWidthType: 'standard',
        surfaceType: 'hard_court',
        surfaceLayers: 1,
        cleanliness: 'medium',
        lightingType: 'fluorescent',
        lightingLux: 380,
        hasAntiGlare: false,
        noiseLevel: 58,
        ventilation: 'open',
        freeParking: true,
        parkingType: 'motorcycle',
        hasLockerRoom: false,
        hasToilet: true,
        toiletQuality: 3,
        hasCanteen: false,
        hasFreeWifi: false,
        standardBallBrand: 'Head',
        hasRacketRental: false,
        images: ['/images/thanhxuan-tennis1.jpg'],
        ratingSurface: 3.6,
        ratingLighting: 3.5,
        ratingCleanliness: 3.4,
        ratingAmenities: 3.0,
        ratingPrice: 4.3,
        ratingService: 3.5,
        ratingOverall: 3.6,
        ownerId: owners[2].id,
        courts: [
          { number: 1, sportType: 'tennis', priceWeekdayMorning: 120000, priceWeekdayAfternoon: 160000, priceWeekdayEvening: 220000, priceWeekendMorning: 160000, priceWeekendAfternoon: 200000, priceWeekendEvening: 260000, operatingHoursStart: '06:00', operatingHoursEnd: '21:30' }
        ]
      }
    ];

    console.log('🏟️  Creating venues...');

    for (const venueData of venues) {
      const courts = venueData.courts;
      delete venueData.courts;

      const venue = await prisma.venue.create({
        data: {
          ...venueData,
          courts: {
            create: courts
          }
        }
      });

      console.log(`✅ Created: ${venue.name} (${venue.sportType})`);
    }

    console.log('🎉 Seed completed successfully!');
    console.log(`📊 Created ${venues.length} venues with multiple courts`);
    console.log(`   - Badminton: 20 venues`);
    console.log(`   - Football: 6 venues`);
    console.log(`   - Tennis: 4 venues`);

  } catch (error) {
    console.error('❌ Seed error:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
};

seedData();
